name: Jake Vosloo

theme: jekyll-theme-slate
title: Welcome to Jake Vosloo's site.
description: Random rambling to follow...
baseurl: /JPVPersonalWebsite
avatar: https://avatars2.githubusercontent.com/u/6603409?s=460&u=a1d5b374938401961bc99d376ca47433362e6c15
disqus:
google_analytics:
permalink: /:title/

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
