# Welcome to Jekyll!
# 
title: "Welcome to Jake Vosloo's site."
email: your-email@example.com
description: Random rambling to follow...
baseurl: /JPVPersonalWebsite
# avatar: https://avatars2.githubusercontent.com/u/6603409?s=460&u=a1d5b374938401961bc99d376ca47433362e6c15
# disqus:
# google_analytics:
# permalink: /:title/

# Build settings
theme: jekyll-theme-slate
# permalink: /:categories/:title/

# Exclude these files from your production _site
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME